using System;
using System.Collections.Generic;
using Godot;

namespace Betauer.Core.Math.PoissonDiskSampling; 

public class PoissonSampler2D {
    /// <summary>
    /// The point generated by the poisson sampler in the las Generate() call.
    /// </summary>
    public List<Vector2> Samples { get; protected set; }

    /// <summary>
    /// The width of the domain of the sampler. This is the maximum <c>x</c> value in a generated point.
    /// </summary>
    public float Width { get; protected set; }

    /// <summary>
    /// The height of the domain of the sampler. This is the maximum <c>y</c> value in a generated point.
    /// </summary>
    public float Height { get; protected set; }

    /// <summary>
    /// The maximum number of attempts to generate a valid new point.
    /// The higher this value, the higher the coverage of the sampler but an increased runtime cost.
    /// </summary>
    public int RejectionLimit { get; }
    
    public Func<Vector2, bool>? PointValidator { get; set; }

    public PoissonSampler2D(float width, float height, Func<Vector2, bool>? pointValidator, int rejectionLimit) {
        Width = width;
        Height = height;
        PointValidator = pointValidator;
        RejectionLimit = rejectionLimit;
    }

    
    /// <summary>
    /// Generate a new random point in the annulus around the provided point.
    /// </summary>
    /// <param name="random"></param>
    /// <param name="point"></param>
    /// <param name="radius"></param>
    /// <returns></returns>
    public static Vector2 GenerateRandomPointInAnnulus(Random random, ref Vector2 point, float radius) {
        var min = radius;
        var max = radius * 2.0f;
        var distance = ((float)random.NextDouble() * (max - min)) + min;
        var angle = (float)random.NextDouble() * Mathf.Tau;
        return new Vector2(
            point.X + (float)System.Math.Cos(angle) * distance,
            point.Y + (float)System.Math.Sin(angle) * distance);
    }
    
    /// <summary>
    /// Is the point within bounds of the sample domain?
    /// </summary>
    /// <param name="sample"></param>
    /// <returns></returns>
    public bool IsSampleOutOfBounds(ref Vector2 sample) {
        return sample.X < 0.0f || sample.X > Width || sample.Y < 0.0f || sample.Y > Height || (PointValidator != null && !PointValidator(sample));
    }

}