name: Integration tests

on: push





env:
  GODOT_VERSION: 3.4.2
  GODOT_VERSION_MODIFIER: "stable.mono"
  EXPORT_NAME: veronenger
  GAME_SUBDIRECTORY: project.godot
  CUSTOM_ICON: "false"
  GITHUB_WORKSPACE: "/workspace"

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.4.2

    steps:

      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1

      # ======================================================
      # pull deps and build
      # ======================================================
      # copy the godot DLLs where they are expected
      - name: Setup Godot dlls
        run: |
          mkdir -p .mono/assemblies/Debug
          mkdir -p DemoGame/.mono/assemblies/Debug
          cp /usr/local/bin/GodotSharp/Api/Debug/* .mono/assemblies/Debug
          cp /usr/local/bin/GodotSharp/Api/Debug/* DemoGame/.mono/assemblies/Debug

      # build the solution
      - name: Build
        run: |
          msbuild Betauer.sln /restore /t:Build "/p:Configuration=Debug" /v:normal
          msbuild DemoGame/Betauer.sln /restore /t:Build "/p:Configuration=Debug" /v:normal

      # run dotnet unit tests
      - name: Test
        run: |
          godot -s TestRunner.cs --no-window
          godot --path DemoGame -s Tests/TestRunner.cs --no-window

