name: Integration tests

on: push





env:
  GODOT_VERSION: 3.4.2
  GODOT_VERSION_MODIFIER: "stable.mono"
  EXPORT_NAME: veronenger
  GAME_SUBDIRECTORY: project.godot
  CUSTOM_ICON: "false"
  GITHUB_WORKSPACE: "/workspace"

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.4.2

    steps:

      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      # ======================================================
      # pull deps and build
      # ======================================================
      # copy the godot DLLs where they are expected
      - name: Setup Godot dlls
        run: |
          mkdir -p .mono/assemblies/Debug
          mkdir -p DemoGame/.mono/assemblies/Debug
          cp /usr/local/bin/GodotSharp/Api/Debug/* .mono/assemblies/Debug
          cp /usr/local/bin/GodotSharp/Api/Debug/* DemoGame/.mono/assemblies/Debug

      # build the solution
      - name: Build
        run: |
          dotnet build
          cd DemoGame
          dotnet build

      # run dotnet unit tests
      - name: Test
        run: |
          godot -s TestRunner.cs --no-window
          cd DemoGame
          godot -s Tests/TestRunner.cs --no-window

